### PR TITLE
improve redistemplate injection& fix http require class

### PR DESCRIPTION
**Pull request by Dream2Land**
1.improve redistemplate injection，support "stringRedisTemplate" bean or "redisTemplate" bean for who has already in application rather than StringRedisTemplate.class instance strick rule
2.fix http require class. for mp starter,if not config dependcies of okhttp&jodd-http in pom.xml,there would tips "required .class" 
3.replace JedisPoolAbstract with interface Pool<Jedis> jedisPool; for better matching with mp-common definition

### CODE REVIEW

**Comment by binarywang** [comment]
请注意代码缩进格式，使用editconfig插件，统一代码风格，谢谢

**Comment by Dream2Land** [comment]
> 请注意代码缩进格式，使用editconfig插件，统一代码风格，谢谢

ok,之前没有搞过，都是用eclipse自带的，我下个看看

**Comment by binarywang** [comment]
啥情况？怎么还删除东西了？

**Comment by binarywang** [comment]
貌似缩进格式还没修复

**Pull request merged**
